[package]
name = "client-template"
version = "0.1.0"
edition = "2021"

[lib]
name = "client_template"
path = "src/lib.rs"

[dependencies]
progenitor-client = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
progenitor = { workspace = true }
serde_json = { workspace = true }
openapiv3 = { workspace = true }
