# Copyright 2025 Edgecast Cloud LLC.
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

[package]
name = "bugview-client"
version = "0.1.0"
edition = "2021"

[lib]
name = "bugview_client"
path = "src/lib.rs"

[dependencies]
progenitor-client = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
progenitor = { workspace = true }
serde_json = { workspace = true }
openapiv3 = { workspace = true }
