# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Copyright 2025 Edgecast Cloud LLC.

[package]
name = "openapi-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
dropshot = { workspace = true }
dropshot-api-manager = { workspace = true }
dropshot-api-manager-types = { workspace = true }
anyhow = { workspace = true }
camino = "1.1"
clap = { workspace = true }

[[bin]]
name = "openapi-manager"
path = "src/main.rs"
