# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Copyright 2026 Edgecast Cloud LLC.

[package]
name = "rebalancer-manager-client"
version = "0.1.0"
edition.workspace = true
description = "Progenitor-generated client for the Rebalancer Manager API"

[lints]
workspace = true

[lib]
name = "rebalancer_manager_client"
path = "src/lib.rs"

[dependencies]
progenitor-client = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
progenitor = { workspace = true }
serde_json = { workspace = true }
openapiv3 = { workspace = true }
