# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Copyright 2026 Edgecast Cloud LLC.

[package]
name = "bugview-service"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "bugview-service"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
askama = { workspace = true}
async-trait = "0.1"
base64 = "0.22"
bugview-api = { path = "../../apis/bugview-api" }
dropshot = { workspace = true }
http = "1.1"
indexmap = "2"
jira-api = { path = "../../apis/jira-api" }
jira-client = { path = "../../clients/internal/jira-client" }
rand = "0.9"
reqwest = { workspace = true, features = ["json"] }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = "2.5"
urlencoding = "2.1"

[dev-dependencies]
dropshot = { workspace = true }
jira-client = { path = "../../clients/internal/jira-client" }
jira-stub-server = { path = "../jira-stub-server" }
reqwest = { workspace = true }
